//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace programSaptamanal
{
    using System;
    using System.Collections.Generic;
    
    public partial class importFrh
    {
        public int id { get; set; }
        public string dataMeci { get; set; }
        public string oraMeci { get; set; }
        public string salaMeci { get; set; }
        public string echipa1 { get; set; }
        public string echipa2 { get; set; }
        public string categorieMeci { get; set; }
    }
}
